### ISSUE TITLE
Dtrain class?

### ISSUE THREAD

**Issue by NKalavros** [willtownes/spatial-factorization-py#2]
Hello! Great idea and glad you're making it into a package. I am having some difficulty with the new implementation and the Dtrain variable Dtrain. I saw in the code it refers to a previous file (preprocess.py). I was able to get this running using those (anndata_to_train_val and prepare_datasets_tf),

**Comment by willtownes** [comment]
Hi thanks for your interest! Sorry about that, I need to migrate more of the code over. In the meantime, you can find the pretrain functions here: https://github.com/willtownes/nsf-paper/blob/main/utils/preprocess.py . Let me know if you have any further questions. 

Keeping this issue open to remind myself to move some of the pretrain functions over.

**Comment by willtownes** [comment]
This has now been incorporated into the package thanks to @alam-shahul commit dfd6428fe79b9c387ece2551038d7fcca231cabc
